# Generated from current truck merged tables.
# Edit BORDER_CUSTOMS manually if any post is wrongly classified or missing.
# Value-count lists are sorted descending by total occurrence across merged truck data.

BORDER_CUSTOMS = [
    'Qırmızı körpü g/p',
    'Samur g/p',
    'Mazımqara g/p',
    'Culfa g/p',
    'Astara g/p',
    'Biləsuvar g/p',
    'Sədərək g/p',
    'Bakı BGİ',
    'Xanoba g/p',
    'Biləsuvar Keçid məntəqəsi',
    'Beynəlxalq Dəniz Ticarət Limanı g/p',
    'Astara G/İ',
    'Şahtaxtı g/p',
    'Biləsuvar G/İ',
    'Astara Keçid məntəqəsi',
    'Şirvanlı g/p',
    'Cənub-Astara g/p',
    'Xaçmaz Gömrük İdarəsi',
    'Qoşa təpə g/p',
    'Culfa G/İ',
    'Tovuz G/İ',
    'Dəniz nəqliyyatı və Enerji resursları Baş Gömrük İdarəsi',
    'Şimal Ərazi Baş Gömrük İdarəsi',
    'Sədərək G/İ',
    'Enerji resursları və dəniz nəqliyyatında BG/İ',
    'Mazımçay g/p',
    'Astara modul tipli g/p',
    'Eyvazlı gömrük postu',
    'Baki Beynalxalq Dəniz Limani',
    'Lənkəran g/p',
    'Şahtaxtı G/İ',
    'Gəncə hava limanı g/p',
    'Qubadlı gömrük postu',
    'Azərterminalkompleks',
    'DGK',
]

BORDER_CUSTOMS_VALUE_COUNTS = [
    ('Qırmızı körpü g/p', 3352025),
    ('Samur g/p', 2242629),
    ('Mazımqara g/p', 810355),
    ('Culfa g/p', 674467),
    ('Astara g/p', 653091),
    ('Biləsuvar g/p', 628388),
    ('Sədərək g/p', 617343),
    ('Bakı BGİ', 443025),
    ('Xanoba g/p', 366985),
    ('Biləsuvar Keçid məntəqəsi', 335384),
    ('Beynəlxalq Dəniz Ticarət Limanı g/p', 333526),
    ('Astara G/İ', 263370),
    ('Şahtaxtı g/p', 252973),
    ('Biləsuvar G/İ', 247890),
    ('Astara Keçid məntəqəsi', 228110),
    ('Şirvanlı g/p', 173222),
    ('Cənub-Astara g/p', 144317),
    ('Xaçmaz Gömrük İdarəsi', 125742),
    ('Qoşa təpə g/p', 67866),
    ('Culfa G/İ', 56993),
    ('Tovuz G/İ', 36359),
    ('Dəniz nəqliyyatı və Enerji resursları Baş Gömrük İdarəsi', 34385),
    ('Şimal Ərazi Baş Gömrük İdarəsi', 33524),
    ('Sədərək G/İ', 21552),
    ('Enerji resursları və dəniz nəqliyyatında BG/İ', 21325),
    ('Mazımçay g/p', 20861),
    ('Astara modul tipli g/p', 14948),
    ('Eyvazlı gömrük postu', 13808),
    ('Baki Beynalxalq Dəniz Limani', 11434),
    ('Lənkəran g/p', 7421),
    ('Şahtaxtı G/İ', 577),
    ('Gəncə hava limanı g/p', 357),
    ('Qubadlı gömrük postu', 348),
    ('Azərterminalkompleks', 29),
    ('DGK', 11),
]

OTHER_CUSTOMS_VALUE_COUNTS = [
    ('İpək Yolu g/p', 571908),
    ('Sumqayıt Gİ', 189145),
    ('"Naxçıvan Karqo Terminalı" g/p', 149511),
    ('NŞGİ', 107567),
    ('Xocahəsən g/p', 91514),
    ('Xudat g/p', 83251),
    ('Aksizli mallar üzrə BGİ', 50666),
    ('Xocəsən g/p', 46337),
    ('Gəncə G/İ', 38462),
    ('Sumqayıt BGİ', 32290),
    ('Qərb Ərazi BGİ', 29147),
    ('Cənub Ərazi BG/İ', 27176),
    ('Liman g/p', 24122),
    ('Tovuz g/p', 19947),
    ('Yevlax Gömrük Postu', 17872),
    ('Abşeron Gömrük Postu', 16280),
    ('Sahil g/p', 15478),
    ('"Şirvan" gömrük postu', 14328),
    ('Yevlax g/p', 13750),
    ('Şirvan g/p', 13508),
    ('"Logistika Mərkəzi" gömrük postu', 9358),
    ('HNBGİ', 6057),
    ('Balakən g/p', 5637),
    ('Balakən G/İ', 5436),
    ('Azad və XIZ üzrə Gömrük İdarəsi', 5052),
    ('Hövsan Dəniz g/p', 5024),
    ('Şərqi Zəngəzur Gömrük İdarəsi', 4966),
    ('Qəbələ g/p', 4264),
    ('Xudafərin g/p', 3846),
    ('Poçt göndərişləri g/p', 3747),
    ('Kürdəmir g/p', 3324),
    ('Xudafərin Gömrük Postu', 2943),
    ('Bakı Karqo Terminalı Hava Liman g/p', 2510),
    ('Qəbələ Gömrük Postu', 2357),
    ('Zirə Dəniz g/p', 2203),
    ('"Poçt və ekspres daşımalar" gömrük postu', 2046),
    ('Şirvan G/İ', 1621),
    ('Şəki g/p', 1617),
    ('Yevlax G/İ', 1601),
    ('"Kürdəmir" gömrük postu', 1410),
    ('Aksiz BG/İ', 1000),
    ('Xudat  g/p', 966),
    ('Şəki Gömrük Postu', 914),
    ('Enerji G/İ', 834),
    ('Cargonyx GNZ', 797),
    ('Bakı KOB g/p', 749),
    ('Avtonəqliyyat BGİ', 505),
    ('Xudafərin G/İ', 456),
    ('Xırdalan g/p', 198),
    ('Naxçıvan BGİ', 174),
    ('COP29', 125),
    ('Yeni Sanqaçal g/p', 85),
    ('NHNGİ', 74),
    ('NHLGP', 66),
    ('WUF13', 56),
    ('Astara Dəmiryolu g/p', 51),
    ('Keşlə g/p', 37),
    ('Azad və Xüsusi İqtisadi Zonalar üzrə Gömrük İdarəsi', 31),
    ('Qaradağ g/p', 15),
    ('Naxçıvan hava limanı g/p', 11),
    ('Dübəndi g/p', 8),
    ('Sadıxlı g/p', 6),
    ('Güzdək g/p', 2),
    ('Mingəçevir Gömrük Postu', 2),
    ('NDGK', 2),
]
