goods_nomenclature_english_data = [{'section': 'I - LIVE ANIMALS; ANIMAL PRODUCTS',
  'categories': [{'code': '01', 'name': 'Live animals'},
                 {'code': '02', 'name': 'Meat and edible meat offal'},
                 {'code': '03', 'name': 'Fish and crustaceans, molluscs and other aquatic invertebrates'},
                 {'code': '04',
                  'name': 'Dairy produce; bird eggs; natural honey; edible products of animal origin, not elsewhere '
                          'specified or included'},
                 {'code': '05', 'name': 'Products of animal origin, not elsewhere specified or included'}]},
 {'section': 'II - VEGETABLE PRODUCTS',
  'categories': [{'code': '06',
                  'name': 'Live trees and other plants; bulbs, roots and the like; cut flowers and ornamental foliage'},
                 {'code': '07', 'name': 'Edible vegetables and certain roots and tubers'},
                 {'code': '08', 'name': 'Edible fruit and nuts; peel of citrus fruit or melons'},
                 {'code': '09', 'name': 'Coffee, tea, mate and spices'},
                 {'code': '10', 'name': 'Cereals'},
                 {'code': '11', 'name': 'Products of the milling industry; malt; starches; inulin; wheat gluten'},
                 {'code': '12',
                  'name': 'Oil seeds and oleaginous fruits; miscellaneous grains, seeds and fruit; industrial or '
                          'medicinal plants; straw and fodder'},
                 {'code': '13', 'name': 'Lac; gums, resins and other vegetable saps and extracts'},
                 {'code': '14',
                  'name': 'Vegetable plaiting materials; vegetable products not elsewhere specified or included'}]},
 {'section': 'III - ANIMAL, VEGETABLE OR MICROBIAL FATS AND OILS AND THEIR CLEAVAGE PRODUCTS; PREPARED EDIBLE FATS; '
             'ANIMAL OR VEGETABLE WAXES',
  'categories': [{'code': '15',
                  'name': 'Animal, vegetable or microbial fats and oils and their cleavage products; prepared edible '
                          'fats; animal or vegetable waxes'}]},
 {'section': 'IV - PREPARED FOODSTUFFS; BEVERAGES, SPIRITS AND VINEGAR; TOBACCO AND MANUFACTURED TOBACCO SUBSTITUTES',
  'categories': [{'code': '16',
                  'name': 'Preparations of meat, fish, crustaceans, molluscs or other aquatic invertebrates'},
                 {'code': '17', 'name': 'Sugars and sugar confectionery'},
                 {'code': '18', 'name': 'Cocoa and cocoa preparations'},
                 {'code': '19', 'name': 'Preparations of cereals, flour, starch or milk; pastry products'},
                 {'code': '20', 'name': 'Preparations of vegetables, fruit, nuts or other parts of plants'},
                 {'code': '21', 'name': 'Miscellaneous edible preparations'},
                 {'code': '22', 'name': 'Beverages, spirits and vinegar'},
                 {'code': '23', 'name': 'Residues and waste from the food industries; prepared animal fodder'},
                 {'code': '24', 'name': 'Tobacco and manufactured tobacco substitutes'}]},
 {'section': 'V - MINERAL PRODUCTS',
  'categories': [{'code': '25', 'name': 'Salt; sulphur; earths and stone; plastering materials, lime and cement'},
                 {'code': '26', 'name': 'Ores, slag and ash'},
                 {'code': '27',
                  'name': 'Mineral fuels, mineral oils and products of their distillation; bituminous substances; '
                          'mineral waxes'}]},
 {'section': 'VI - PRODUCTS OF THE CHEMICAL OR ALLIED INDUSTRIES',
  'categories': [{'code': '28',
                  'name': 'Inorganic chemicals; organic or inorganic compounds of precious metals, rare-earth metals, '
                          'radioactive elements or isotopes'},
                 {'code': '29', 'name': 'Organic chemicals'},
                 {'code': '30', 'name': 'Pharmaceutical products'},
                 {'code': '31', 'name': 'Fertilizers'},
                 {'code': '32',
                  'name': 'Tanning or dyeing extracts; tannins and derivatives; dyes, pigments and other colouring '
                          'matter; paints and varnishes; putty and other mastics; inks'},
                 {'code': '33', 'name': 'Essential oils and resinoids; perfumery, cosmetic or toilet preparations'},
                 {'code': '34',
                  'name': 'Soap, organic surface-active agents, washing preparations, lubricating preparations, '
                          'artificial waxes, prepared waxes, polishing preparations, candles and similar articles, '
                          'modelling pastes and dental waxes'},
                 {'code': '35', 'name': 'Albuminoidal substances; modified starches; glues; enzymes'},
                 {'code': '36',
                  'name': 'Explosives; pyrotechnic products; matches; pyrophoric alloys; certain combustible '
                          'preparations'},
                 {'code': '37', 'name': 'Photographic or cinematographic goods'},
                 {'code': '38', 'name': 'Miscellaneous chemical products'}]},
 {'section': 'VII - PLASTICS AND ARTICLES THEREOF; RUBBER AND ARTICLES THEREOF',
  'categories': [{'code': '39', 'name': 'Plastics and articles thereof'},
                 {'code': '40', 'name': 'Rubber and articles thereof'}]},
 {'section': 'VIII - RAW HIDES AND SKINS, LEATHER, FURSKINS AND ARTICLES THEREOF; SADDLERY AND HARNESS; TRAVEL GOODS, '
             'HANDBAGS AND SIMILAR CONTAINERS; ARTICLES OF ANIMAL GUT',
  'categories': [{'code': '41', 'name': 'Raw hides and skins, other than furskins, and leather'},
                 {'code': '42',
                  'name': 'Articles of leather; saddlery and harness; travel goods, handbags and similar containers; '
                          'articles of animal gut'},
                 {'code': '43', 'name': 'Furskins and artificial fur; manufactures thereof'}]},
 {'section': 'IX - WOOD AND ARTICLES OF WOOD; WOOD CHARCOAL; CORK AND ARTICLES OF CORK; MANUFACTURES OF STRAW, ESPARTO '
             'OR OTHER PLAITING MATERIALS',
  'categories': [{'code': '44', 'name': 'Wood and articles of wood; wood charcoal'},
                 {'code': '45', 'name': 'Cork and articles of cork'},
                 {'code': '46',
                  'name': 'Manufactures of straw, esparto or other plaiting materials; basketware and wickerwork'}]},
 {'section': 'X - PULP OF WOOD OR OTHER FIBROUS CELLULOSIC MATERIAL; RECOVERED PAPER OR PAPERBOARD; PAPER, PAPERBOARD '
             'AND ARTICLES THEREOF',
  'categories': [{'code': '47',
                  'name': 'Pulp of wood or other fibrous cellulosic material; recovered paper or paperboard'},
                 {'code': '48', 'name': 'Paper and paperboard; articles of paper pulp, paper or paperboard'},
                 {'code': '49',
                  'name': 'Printed books, newspapers, pictures and other products of the printing industry; '
                          'manuscripts, typescripts and plans'}]},
 {'section': 'XI - TEXTILES AND TEXTILE ARTICLES',
  'categories': [{'code': '50', 'name': 'Silk'},
                 {'code': '51', 'name': 'Wool, fine or coarse animal hair; horsehair yarn and woven fabric'},
                 {'code': '52', 'name': 'Cotton'},
                 {'code': '53', 'name': 'Other vegetable textile fibres; paper yarn and woven fabrics of paper yarn'},
                 {'code': '54', 'name': 'Man-made filaments; strip and the like of man-made textile materials'},
                 {'code': '55', 'name': 'Man-made staple fibres'},
                 {'code': '56',
                  'name': 'Wadding, felt and nonwovens; special yarns; twine, cordage, ropes and cables and articles '
                          'thereof'},
                 {'code': '57', 'name': 'Carpets and other textile floor coverings'},
                 {'code': '58',
                  'name': 'Special woven fabrics; tufted textile fabrics; lace; tapestries; trimmings; embroidery'},
                 {'code': '59',
                  'name': 'Impregnated, coated, covered or laminated textile fabrics; textile articles for technical '
                          'uses'},
                 {'code': '60', 'name': 'Knitted or crocheted fabrics'},
                 {'code': '61', 'name': 'Articles of apparel and clothing accessories, knitted or crocheted'},
                 {'code': '62', 'name': 'Articles of apparel and clothing accessories, not knitted or crocheted'},
                 {'code': '63',
                  'name': 'Other made-up textile articles; sets; worn clothing and worn textile articles; rags'}]},
 {'section': 'XII - FOOTWEAR, HEADGEAR, UMBRELLAS, SUN UMBRELLAS, WALKING-STICKS, SEAT-STICKS, WHIPS AND PARTS '
             'THEREOF; PREPARED FEATHERS AND ARTICLES MADE THEREWITH',
  'categories': [{'code': '64', 'name': 'Footwear, gaiters and the like; parts of such articles'},
                 {'code': '65', 'name': 'Headgear and parts thereof'},
                 {'code': '66',
                  'name': 'Umbrellas, sun umbrellas, walking-sticks, seat-sticks, whips, riding-crops and parts '
                          'thereof'},
                 {'code': '67',
                  'name': 'Prepared feathers and down and articles made of feathers or down; artificial flowers; '
                          'articles of human hair'}]},
 {'section': 'XIII - ARTICLES OF STONE, PLASTER, CEMENT, ASBESTOS, MICA OR SIMILAR MATERIALS; CERAMIC PRODUCTS; GLASS '
             'AND GLASSWARE',
  'categories': [{'code': '68', 'name': 'Articles of stone, plaster, cement, asbestos, mica or similar materials'},
                 {'code': '69', 'name': 'Ceramic products'},
                 {'code': '70', 'name': 'Glass and glassware'}]},
 {'section': 'XIV - NATURAL OR CULTURED PEARLS, PRECIOUS OR SEMI-PRECIOUS STONES, PRECIOUS METALS, METALS CLAD WITH '
             'PRECIOUS METAL, AND ARTICLES THEREOF; JEWELLERY; COIN',
  'categories': [{'code': '71',
                  'name': 'Natural or cultured pearls, precious or semi-precious stones, precious metals, metals clad '
                          'with precious metal and articles thereof; jewellery; coin'}]},
 {'section': 'XV - BASE METALS AND ARTICLES OF BASE METAL',
  'categories': [{'code': '72', 'name': 'Iron and steel'},
                 {'code': '73', 'name': 'Articles of iron or steel'},
                 {'code': '74', 'name': 'Copper and articles thereof'},
                 {'code': '75', 'name': 'Nickel and articles thereof'},
                 {'code': '76', 'name': 'Aluminium and articles thereof'},
                 {'code': '78', 'name': 'Lead and articles thereof'},
                 {'code': '79', 'name': 'Zinc and articles thereof'},
                 {'code': '80', 'name': 'Tin and articles thereof'},
                 {'code': '81', 'name': 'Other base metals; cermets; articles thereof'},
                 {'code': '82', 'name': 'Tools, implements, cutlery, spoons and forks, of base metal; parts thereof'},
                 {'code': '83', 'name': 'Miscellaneous articles of base metal'}]},
 {'section': 'XVI - MACHINERY AND MECHANICAL APPLIANCES; ELECTRICAL EQUIPMENT; PARTS THEREOF; SOUND RECORDERS AND '
             'REPRODUCERS, TELEVISION IMAGE AND SOUND RECORDERS AND REPRODUCERS',
  'categories': [{'code': '84',
                  'name': 'Nuclear reactors, boilers, machinery and mechanical appliances; parts thereof'},
                 {'code': '85',
                  'name': 'Electrical machinery and equipment and parts thereof; sound recorders and reproducers; '
                          'television image and sound recorders and reproducers; parts and accessories'}]},
 {'section': 'XVII - VEHICLES, AIRCRAFT, VESSELS AND ASSOCIATED TRANSPORT EQUIPMENT',
  'categories': [{'code': '86',
                  'name': 'Railway or tramway locomotives, rolling-stock and parts thereof; railway or tramway track '
                          'fixtures and fittings; signalling equipment'},
                 {'code': '87',
                  'name': 'Vehicles other than railway or tramway rolling-stock, and parts and accessories thereof'},
                 {'code': '88', 'name': 'Aircraft, spacecraft, and parts thereof'},
                 {'code': '89', 'name': 'Ships, boats and floating structures'}]},
 {'section': 'XVIII - OPTICAL, PHOTOGRAPHIC, CINEMATOGRAPHIC, MEASURING, CHECKING, PRECISION, MEDICAL OR SURGICAL '
             'INSTRUMENTS AND APPARATUS; CLOCKS AND WATCHES; MUSICAL INSTRUMENTS',
  'categories': [{'code': '90',
                  'name': 'Optical, photographic, cinematographic, measuring, checking, precision, medical or surgical '
                          'instruments and apparatus; parts and accessories thereof'},
                 {'code': '91', 'name': 'Clocks and watches and parts thereof'},
                 {'code': '92', 'name': 'Musical instruments; parts and accessories thereof'}]},
 {'section': 'XIX - ARMS AND AMMUNITION; PARTS AND ACCESSORIES THEREOF',
  'categories': [{'code': '93', 'name': 'Arms and ammunition; parts and accessories thereof'}]},
 {'section': 'XX - MISCELLANEOUS MANUFACTURED ARTICLES',
  'categories': [{'code': '94',
                  'name': 'Furniture; bedding, mattresses, mattress supports, cushions and similar stuffed '
                          'furnishings; lamps and lighting fittings; illuminated signs and name-plates; prefabricated '
                          'buildings'},
                 {'code': '95', 'name': 'Toys, games and sports requisites; parts and accessories thereof'},
                 {'code': '96', 'name': 'Miscellaneous manufactured articles'}]},
 {'section': 'XXI - WORKS OF ART, COLLECTORS ITEMS AND ANTIQUES',
  'categories': [{'code': '97', 'name': 'Works of art, collectors pieces and antiques'}]}]
