# Generated by Django 6.0.4 on 2026-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('dashboard_view', 'Dashboard view'), ('module_view', 'Module view'), ('submodule_view', 'Submodule view'), ('report_link_click', 'Report link click'), ('report_preview', 'Report preview'), ('report_download_start', 'Report download start')], max_length=50)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'event_type'],
            },
        ),
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('dashboard_view', 'Dashboard view'), ('module_view', 'Module view'), ('submodule_view', 'Submodule view'), ('report_link_click', 'Report link click'), ('report_preview', 'Report preview'), ('report_download_start', 'Report download start')], max_length=50)),
                ('target_url', models.CharField(blank=True, max_length=700)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
