# Generated by Django 6.0.4 on 2026-04-30 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('catalog', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiondailystat',
            name='dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.dashboarddefinition'),
        ),
        migrations.AddField(
            model_name='interactiondailystat',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.module'),
        ),
        migrations.AddField(
            model_name='interactiondailystat',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.reportdefinition'),
        ),
        migrations.AddField(
            model_name='interactiondailystat',
            name='submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.submodule'),
        ),
        migrations.AddField(
            model_name='interactionevent',
            name='dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.dashboarddefinition'),
        ),
        migrations.AddField(
            model_name='interactionevent',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.module'),
        ),
        migrations.AddField(
            model_name='interactionevent',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportdefinition'),
        ),
        migrations.AddField(
            model_name='interactionevent',
            name='submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.submodule'),
        ),
        migrations.AddField(
            model_name='interactionevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='interactiondailystat',
            unique_together={('date', 'event_type', 'module', 'submodule', 'dashboard', 'report')},
        ),
    ]
