# Generated by Django 6.0.4 on 2026-04-30 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('docx', 'Microsoft Word')], default='docx', max_length=20)),
                ('generator_key', models.CharField(max_length=100)),
                ('template_path', models.CharField(blank=True, max_length=700)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='catalog.submodule')),
            ],
            options={
                'ordering': ['submodule__module__order', 'submodule__order', 'order', 'name'],
                'unique_together': {('submodule', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ReportDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(default='docx', max_length=20)),
                ('generated_file_path', models.CharField(blank=True, max_length=700)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.module')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportdefinition')),
                ('submodule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.submodule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
