# Generated by Django 6.0.4 on 2026-04-30 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Submodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='catalog.module')),
            ],
            options={
                'ordering': ['module__order', 'order', 'name'],
                'unique_together': {('module', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_import', models.BooleanField(default=False)),
                ('can_manage', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='catalog.module')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submodule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='catalog.submodule')),
            ],
            options={
                'ordering': ['module__name', 'submodule__name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('rsync', 'Rsync'), ('local', 'Local folder')], default='rsync', max_length=20)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('destination_subdir', models.CharField(blank=True, max_length=255)),
                ('accepted_extensions', models.CharField(default='.xlsx,.xls,.xlsm,.csv', max_length=255)),
                ('parser_key', models.CharField(blank=True, max_length=100)),
                ('processor_key', models.CharField(blank=True, max_length=100)),
                ('target_model_key', models.CharField(blank=True, max_length=100)),
                ('duplicate_strategy', models.CharField(default='prevent', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('submodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='catalog.submodule')),
            ],
            options={
                'ordering': ['submodule__module__order', 'submodule__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('modules', models.ManyToManyField(blank=True, related_name='dashboards', to='catalog.module')),
                ('submodules', models.ManyToManyField(blank=True, related_name='dashboards', to='catalog.submodule')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
