# Generated by Django 6.0.4 on 2026-04-30 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('filesync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('skipped', 'Skipped')], default='success', max_length=20)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('duplicate_decision', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stored_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filesync.storedfile')),
                ('submodule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.submodule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_key', models.CharField(max_length=100)),
                ('file_path', models.CharField(blank=True, max_length=700)),
                ('status', models.CharField(default='success', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='imports.importjob')),
            ],
        ),
        migrations.CreateModel(
            name='TransitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('corridor', models.CharField(blank=True, max_length=255)),
                ('post', models.CharField(blank=True, max_length=255)),
                ('cargo_name', models.CharField(blank=True, max_length=255)),
                ('weight_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_records', to='imports.importjob')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_records', to='filesync.storedfile')),
            ],
            options={
                'ordering': ['source_file', 'row_number'],
                'unique_together': {('source_file', 'row_number')},
            },
        ),
    ]
